### ISSUE TITLE
Inconsistency in path separation on Unix

### ISSUE THREAD

**Issue by arashgmn** [MoritzB90/PyRID#1]
Hi,

There's an issue with the `Hard_Sphere_Fluid.py` file (and maybe others). It runs until the following `FileNotFoundError`: 

```FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/arash/PyRID/validation\Files\hdf5\Hard_Sphere_Fluid.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)```

The h5 file is there. The issue is the slash/back-slash conversion of windows vs. Unix (note the path). I'm using Ubuntu.

**Comment by MoritzB90** [comment]
Hi,

Thanks for reporting this! I had build some of the paths manually and did not thoroughly test PyRID for Linux. I have just pushed an update that resolves this issue. Paths are now all handled via Python's Path library so you should no longer have issues with paths on different operating systems as long as you use the forward slash character between folder names (also on Windows).
